version: '3.8'

services:
  cricket.db:
    image: mysql:8.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cricket_db
    volumes:
      - cricketdbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -ppassword cricket_db -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 10

volumes:
  cricketdbdata:
