version: '3.8'

services:
  cricket.api:
    build:
      context: .
      target: Dev
    image: cricket.api
    working_dir: /app
    volumes:
      - .:/app
    depends_on: 
      - cricket.db
      - cricket.db.migrations
    environment:
      - DATABASE_URL=root:password@tcp(cricket.db:3306)/cricket_db?parseTime=true
    ports:
      - 8080:8080
    restart: unless-stopped

  cricket.db:
    image: mysql:8.2.0
    environment:
      - MYSQL_ROOT_PASSWORD=password #for testing only, please use environment variable in production
      - MYSQL_DATABASE=cricket_db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -ppassword cricket_db -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 10

  cricket.db.migrations:
    depends_on:
      cricket.db:
        condition: service_healthy
    image: cricket.db.migrations
    build:
      context: ./db/
    command: "'mysql://root:password@tcp(cricket.db:3306)/cricket_db' up"

  dev-cli:
    profiles:
      - dev-cli

    build:
      context: .
      target: Dev
    image: cricket.dev-cli
    working_dir: /app
    volumes:
      - .:/app
    depends_on: 
      - cricket.db
      - cricket.db.migrations
    environment:
      - DATABASE_URL=root:password@tcp(cricket.db:3306)/cricket_db?parseTime=true

    command: sh


volumes:
  mysql:
