// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"
)

type Player struct {
	ID              int64           `json:"id"`
	Name            string          `json:"name"`
	CareerStartYear sql.NullInt64   `json:"career_start_year"`
	CareerEndYear   sql.NullInt64   `json:"career_end_year"`
	Matches         sql.NullInt64   `json:"matches"`
	Inns            sql.NullInt64   `json:"inns"`
	NotOuts         sql.NullInt64   `json:"not_outs"`
	Runs            sql.NullInt64   `json:"runs"`
	HighestScores   sql.NullInt64   `json:"highest_scores"`
	Average         sql.NullFloat64 `json:"average"`
	FacedBalls      sql.NullInt64   `json:"faced_balls"`
	StrikeRate      sql.NullFloat64 `json:"strike_rate"`
	ScoreHundreds   sql.NullInt64   `json:"score_hundreds"`
	ScoreFiftys     sql.NullInt64   `json:"score_fiftys"`
	ScoreZeros      sql.NullInt64   `json:"score_zeros"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
