// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (sql.Result, error)
	GetPlayersByCareerYear(ctx context.Context, arg GetPlayersByCareerYearParams) ([]Player, error)
	GetPlayersOfMostRuns(ctx context.Context) (Player, error)
	GetPlayersOfMostRunsByCareerEndYear(ctx context.Context, careerEndYear sql.NullInt64) (Player, error)
}

var _ Querier = (*Queries)(nil)
